import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { report } from './model.js';
const $=id=>document.getElementById(id),stage=$('stage'),canvas=$('scene');
const buildMode=new URLSearchParams(location.search).get('build')==='1';
let scene,renderer,root,camera,perspective,ortho,controls,width=1,height=1,frame=null,view='overview';
const viewNames={overview:'整体视角',top:'俯视布局',inside:'场内视角'};
function invalidate(){if(frame===null)frame=requestAnimationFrame(render);}
function render(){frame=null;const moving=controls.update();renderer.render(scene,camera);stage.dataset.camera=JSON.stringify({position:camera.position.toArray(),target:controls.target.toArray(),zoom:camera.zoom});if(moving)invalidate();}
function setView(name){view=name;const damping=controls.enableDamping;controls.enableDamping=false;controls.update();camera=name==='top'?ortho:perspective;controls.object=camera;controls.enableRotate=name!=='top';controls.minDistance=name==='inside'?.35:3;controls.maxDistance=60;controls.minZoom=.5;controls.maxZoom=5;controls.maxPolarAngle=name==='inside'?Math.PI*.54:Math.PI*.49;
 if(name==='top'){camera.position.set(0,30,.001);controls.target.set(0,0,0);camera.zoom=1;}
 else if(name==='inside'){camera.fov=67;camera.position.set(.6,1.6,3.65);controls.target.set(-1,1.3,-2.7);}
 else{camera.fov=38;const fit=Math.max(1,1.15/(width/height));camera.position.set(13.2*fit,12.8*fit,17*fit);controls.target.set(0,.65,0);}
 camera.updateProjectionMatrix();controls.update();controls.enableDamping=damping;stage.dataset.view=view;$('view-label').textContent=viewNames[view];document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));invalidate();}
function resize(){const r=stage.getBoundingClientRect();width=Math.max(1,r.width);height=Math.max(1,r.height);renderer.setSize(width,height,false);perspective.aspect=width/height;perspective.updateProjectionMatrix();const half=Math.max(5.25,6.95/(width/height));ortho.left=-half*width/height;ortho.right=half*width/height;ortho.top=half;ortho.bottom=-half;ortho.updateProjectionMatrix();if(view==='overview')setView(view);else invalidate();}
async function saveModel(){const b=$('save');b.disabled=true;$('build-status').textContent='正在保存完整场景…';try{const [{GLTFExporter},{portableCopy}]=await Promise.all([import('three/addons/exporters/GLTFExporter.js'),import('./model.js')]);const exportRoot=portableCopy(root);exportRoot.getObjectByName('Bar_Roof').visible=true;exportRoot.getObjectByName('Bar_Walls').visible=true;const buffer=await new GLTFExporter().parseAsync(exportRoot,{binary:true,onlyVisible:true,maxTextureSize:2048});const response=await fetch('/__save-bar',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:buffer});if(!response.ok)throw new Error(`HTTP ${response.status}`);const saved=await response.json();if(!saved.saved)throw new Error(saved.error||'模型未保存');$('build-status').textContent=`已保存 bar.glb · ${(buffer.byteLength/1024/1024).toFixed(2)} MiB`;stage.dataset.saved='true';$('download').removeAttribute('aria-disabled');}catch(error){$('build-status').textContent=`保存失败：${error.message}`;console.error(error);}finally{b.disabled=false;}}
async function init(){
 renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;
 scene=new THREE.Scene();scene.background=new THREE.Color('#302821');perspective=new THREE.PerspectiveCamera(38,1,.05,160);ortho=new THREE.OrthographicCamera(-7,7,5.25,-5.25,.05,160);camera=perspective;controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.1;controls.screenSpacePanning=false;controls.addEventListener('change',invalidate);controls.addEventListener('start',()=>canvas.style.cursor='grabbing');controls.addEventListener('end',()=>canvas.style.cursor='grab');
 scene.add(new THREE.HemisphereLight('#ffe5bc','#242125',.55));const key=new THREE.DirectionalLight('#ffdab0',1.8);key.position.set(-2,12,9);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-10,right:10,top:9,bottom:-9,near:.2,far:40});key.shadow.normalBias=.025;key.shadow.bias=-.0001;scene.add(key);const fill=new THREE.DirectionalLight('#e7d8c6',.42);fill.position.set(8,6,-2);scene.add(fill);
 const pm=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment(),environment=pm.fromScene(room,.05);scene.environment=environment.texture;scene.environmentIntensity=.26;pm.dispose();room.dispose();
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({color:'#302821',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.19;ground.receiveShadow=true;scene.add(ground);
 document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('reset').addEventListener('click',()=>setView('overview'));for(const [id,name] of [['walls','Bar_Walls'],['roof','Bar_Roof']])$(id).addEventListener('change',e=>{if(root)root.getObjectByName(name).visible=e.target.checked;stage.dataset[id]=String(e.target.checked);invalidate();});
 new ResizeObserver(resize).observe(stage);resize();
 if(buildMode){$('build-bar').hidden=false;$('download').setAttribute('aria-disabled','true');const {buildBar}=await import('./model.js');await document.fonts.ready;root=await buildBar();$('save').disabled=false;$('save').addEventListener('click',saveModel);}
 else{const gltf=await new GLTFLoader().loadAsync('./bar.glb');root=gltf.scene.getObjectByName('Bar_AmberRoom_12x9');if(!root)throw new Error('完整酒吧节点缺失');}
 root.traverse(o=>{if(o.isMesh){o.castShadow=!(Array.isArray(o.material)?o.material:[o.material]).some(m=>m.transparent);o.receiveShadow=true;}});root.getObjectByName('Bar_Roof').visible=false;scene.add(root);const info=report(root);$('scene-report').textContent=JSON.stringify(info);Object.assign(stage.dataset,{ready:'true',source:buildMode?'build':'bar.glb',view:'overview',walls:'true',roof:'false',objects:String(info.editableObjects??root.userData.inventory?.length??0),meshes:String(info.meshes),triangles:String(info.triangles)});$('loading').hidden=true;$('status').textContent=buildMode?'构建已就绪':'完整 GLB 已载入';setView('overview');
}
canvas.addEventListener('webglcontextlost',event=>{event.preventDefault();$('loading').hidden=false;$('loading-message').textContent='绘图已中断，请刷新页面。';stage.dataset.ready='false';});
init().catch(error=>{$('status').textContent='载入失败';$('loading-message').textContent=error.message;console.error(error);});
