import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {CONFIG} from './config.js';
import {report,portableCopy} from './scene-kit.js';
const $=id=>document.getElementById(id),canvas=$('scene'),stage=$('stage'),buildMode=new URLSearchParams(location.search).get('build')==='1';
let renderer,scene,camera,perspective,ortho,controls,root,roof,frame=null,view='overview',width=1,height=1,environment;
function invalidate(){if(frame===null)frame=requestAnimationFrame(render);}
function render(){frame=null;const moving=controls.update();renderer.render(scene,camera);if(moving)invalidate();}
function setView(next){view=next;const damping=controls.enableDamping;controls.enableDamping=false;controls.update();camera=next==='top'?ortho:perspective;controls.object=camera;controls.enableRotate=next!=='top';controls.minDistance=next==='inside'?.35:4;controls.maxDistance=70;controls.minZoom=.5;controls.maxZoom=5;controls.maxPolarAngle=next==='inside'?Math.PI*.55:Math.PI*.485;
 if(next==='top'){camera.position.set(0,35,.001);controls.target.set(0,0,0);camera.zoom=1;}else if(next==='inside'){camera.fov=65;camera.position.set(...CONFIG.inside);controls.target.set(...CONFIG.lookAt);}else{camera.fov=38;const fit=Math.max(1,1.2/(width/height)),scale=Math.max(CONFIG.width,CONFIG.depth)/14;camera.position.set(16*fit*scale,15*fit*scale,21*fit*scale);controls.target.set(0,.7,0);}
 camera.updateProjectionMatrix();controls.update();controls.enableDamping=damping;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));stage.dataset.view=view;invalidate();}
function resize(){const r=stage.getBoundingClientRect();width=Math.max(1,r.width);height=Math.max(1,r.height);renderer.setSize(width,height,false);perspective.aspect=width/height;perspective.updateProjectionMatrix();const half=Math.max(CONFIG.depth/2+.6,(CONFIG.width/2+.6)/(width/height));ortho.left=-half*width/height;ortho.right=half*width/height;ortho.top=half;ortho.bottom=-half;ortho.updateProjectionMatrix();if(view==='overview')setView(view);else invalidate();}
async function save(){const b=$('save-model');b.disabled=true;try{$('save-status').textContent='正在写入完整场景…';const {GLTFExporter}=await import('three/addons/exporters/GLTFExporter.js');const copy=portableCopy(root);copy.getObjectByName(`${CONFIG.prefix}_Roof`).visible=true;const bytes=await new GLTFExporter().parseAsync(copy,{binary:true,onlyVisible:true,maxTextureSize:2048});const res=await fetch('/__save-model',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:bytes});const result=await res.json();if(!res.ok||!result.saved)throw new Error(`HTTP ${res.status}`);$('save-status').textContent=`已保存 ${CONFIG.slug}.glb · ${(bytes.byteLength/1024/1024).toFixed(2)} MB`;stage.dataset.saved='true';stage.dataset.modelBytes=String(bytes.byteLength);$('download').removeAttribute('aria-disabled');}catch(e){$('save-status').textContent=e.message;console.error(e);}finally{b.disabled=false;}}
async function initialize(){renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=CONFIG.exposure;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 scene=new THREE.Scene();scene.background=new THREE.Color(CONFIG.background);perspective=new THREE.PerspectiveCamera(38,1,.04,150);ortho=new THREE.OrthographicCamera(-8,8,6,-6,.05,150);camera=perspective;controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.09;controls.screenSpacePanning=false;controls.addEventListener('change',invalidate);controls.addEventListener('start',()=>canvas.style.cursor='grabbing');controls.addEventListener('end',()=>canvas.style.cursor='grab');
 scene.add(new THREE.HemisphereLight('#f4f9ff','#7b8570',1.3));const sun=new THREE.DirectionalLight('#fff1dc',2.5);sun.position.set(6,12,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12,near:.4,far:40});sun.shadow.normalBias=.025;sun.shadow.bias=-.0001;scene.add(sun);const fill=new THREE.DirectionalLight('#e9effa',.8);fill.position.set(-3,8,-2);scene.add(fill);
 const pm=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();environment=pm.fromScene(room,.05);scene.environment=environment.texture;scene.environmentIntensity=.5;pm.dispose();room.dispose();
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(150,150),new THREE.MeshStandardMaterial({color:CONFIG.background,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.16;ground.receiveShadow=true;scene.add(ground);
 for(const b of document.querySelectorAll('[data-view]'))b.addEventListener('click',()=>setView(b.dataset.view));$('reset').addEventListener('click',()=>setView('overview'));$('roof-toggle').addEventListener('change',e=>{if(roof)roof.visible=e.target.checked;stage.dataset.roof=String(e.target.checked);invalidate();});
 new ResizeObserver(resize).observe(stage);resize();
 if(buildMode){$('build-bar').hidden=false;$('download').setAttribute('aria-disabled','true');await document.fonts.ready;const {buildScene}=await import('./model.js');root=await buildScene();$('save-model').disabled=false;$('save-model').addEventListener('click',save);}else{const gltf=await new GLTFLoader().loadAsync(`./${CONFIG.slug}.glb`);root=gltf.scene.getObjectByName(CONFIG.root);if(!root)throw new Error('模型根节点与模板不一致');}
 root.traverse(o=>{if(o.isMesh){o.castShadow=!(Array.isArray(o.material)?o.material:o.material?[o.material]:[]).some(m=>m.transparent);o.receiveShadow=true;}});roof=root.getObjectByName(`${CONFIG.prefix}_Roof`);if(!roof)throw new Error('模型缺少顶部结构分组');roof.visible=false;scene.add(root);const data=report(root);Object.assign(stage.dataset,{ready:'true',modelSource:buildMode?'build':`${CONFIG.slug}.glb`,meshes:String(data.meshes),editableObjects:String(data.editableObjects),roof:'false'});$('object-count').textContent=`${data.editableObjects} 个独立物件`;$('loading').hidden=true;$('load-status').textContent=buildMode?'源码构建完成':'完整模型已载入';const record=document.createElement('script');record.id='scene-validation';record.type='application/json';record.textContent=JSON.stringify(data);document.body.append(record);setView('overview');
}
initialize().catch(e=>{$('loading').hidden=false;$('load-message').textContent=`载入失败：${e.message}`;$('load-status').textContent='未完成载入';stage.dataset.ready='false';console.error(e);});
