import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { ZONES, PHASES, applyAttendance, sceneReport } from './model.js?v=1';

const $=id=>document.getElementById(id),canvas=$('scene'),stage=$('stage');
const buildMode=new URLSearchParams(location.search).get('build')==='1';
const state={view:'overview',phase:'launch',count:100,labels:true,people:true,mode:'lecture',rig:false,ready:false};
let renderer,scene,camera,controls,root,sun,environment,frame=null;
let ortho,perspective,width=1,height=1,report=null;
const labels=[];const names={overview:'整体视角',top:'俯视布局',inside:'场内视角'};
function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,2800);}
function invalidate(){if(frame===null)frame=requestAnimationFrame(render);}
function render(){frame=null;const moving=controls.update();renderer.render(scene,camera);stage.dataset.camera=camera.position.toArray().map(n=>n.toFixed(3)).join(',');stage.dataset.zoom=String(camera.zoom);updateLabels();if(moving)invalidate();}
function updateLabels(){for(const {element,point} of labels){const p=point.clone().project(camera);element.hidden=!state.labels||state.view==='inside'||p.z>1||p.z< -1||Math.abs(p.x)>1||Math.abs(p.y)>1;element.style.left=`${(p.x*.5+.5)*width}px`;element.style.top=`${(-p.y*.5+.5)*height}px`;}}
function resize(){const rect=stage.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);renderer.setSize(width,height,false);perspective.aspect=width/height;perspective.updateProjectionMatrix();const half=Math.max(10.5,13.6/(width/height));ortho.left=-half*width/height;ortho.right=half*width/height;ortho.top=half;ortho.bottom=-half;ortho.updateProjectionMatrix();if(state.view==='overview')setView('overview');else invalidate();}
function setView(view){state.view=view;const damping=controls.enableDamping;controls.enableDamping=false;controls.update();camera=view==='top'?ortho:perspective;controls.object=camera;controls.enableRotate=view!=='top';controls.minDistance=view==='inside'?.4:10;controls.maxDistance=95;controls.minZoom=.55;controls.maxZoom=5;controls.maxPolarAngle=view==='inside'?Math.PI*.54:Math.PI*.48;
 if(view==='top'){camera.position.set(0,48,.001);controls.target.set(0,0,0);camera.zoom=1;}
 else if(view==='inside'){camera.fov=68;camera.position.set(.08,1.68,5.75);controls.target.set(0,1.9,-6.8);}
 else{camera.fov=36;const fit=Math.max(1,1.24/(width/height));controls.target.set(0,.7,.3);camera.position.set(26*fit,29*fit,34*fit);}
 camera.updateProjectionMatrix();controls.update();controls.enableDamping=damping;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));$('view-label').textContent=names[view];stage.dataset.view=view;invalidate();}
function updateAttendance(){if(!root)return;const visible=applyAttendance(root,state.count,state.phase,state.people,state.mode);$('guest-total').innerHTML=`${state.count}<small> 人</small>`;$('count-value').textContent=state.count;$('phase-clock').textContent=PHASES[state.phase].clock;$('phase-description').textContent=PHASES[state.phase].text;$('attendance-note').textContent=`${state.count-4} 名观众 + 4 位嘉宾 + 4 位工作人员 · ${state.count-4} 把观众椅 + 4 把嘉宾椅。${PHASES[state.phase].guestVisible?'':'本阶段仅工作人员在场。'}固定排位、前排优先；阶段为预设演示。下载为默认 100 人报告快照。`; 
 document.querySelectorAll('[data-phase]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.phase===state.phase)));
 const closed=state.phase==='closed';sun.intensity=closed?1.4:2.2;scene.environmentIntensity=closed?.5:.7;renderer.toneMappingExposure=closed?.9:1.06;
 Object.assign(stage.dataset,{phase:state.phase,visitors:String(state.count),visiblePeople:String(visible),visibleSeats:String(root.getObjectByName('Conference_Seating').children.filter(o=>o.visible).length),guestSeats:'4',mode:state.mode,view:state.view,rig:String(state.rig)});invalidate();}
function selectZone(id){const zone=ZONES.find(z=>z.id===id);document.querySelectorAll('[data-zone]').forEach(b=>b.classList.toggle('active',b.dataset.zone===id));$('selection').hidden=!zone;if(!zone)return;$('selection-number').textContent=`ZONE / ${zone.n}`;$('selection-title').textContent=zone.title;$('selection-copy').textContent=zone.copy;invalidate();}
function bind(){document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.mode===state.mode)));updateAttendance();}));document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-phase]').forEach(b=>b.addEventListener('click',()=>{state.phase=b.dataset.phase;updateAttendance();}));document.querySelectorAll('[data-zone]').forEach(b=>b.addEventListener('click',()=>selectZone(b.dataset.zone)));$('close-selection').addEventListener('click',()=>selectZone(null));$('reset').addEventListener('click',()=>{setView('overview');selectZone(null);});$('labels').addEventListener('change',e=>{state.labels=e.target.checked;invalidate();});$('people').addEventListener('change',e=>{state.people=e.target.checked;updateAttendance();});$('rig').addEventListener('change',e=>{state.rig=e.target.checked;if(root)root.getObjectByName('Conference_Roof').visible=state.rig;stage.dataset.rig=String(state.rig);invalidate();});$('guest-count').addEventListener('input',e=>{state.count=Number(e.target.value);updateAttendance();});
 $('snapshot').addEventListener('click',()=>{if(!state.ready)return;renderer.render(scene,camera);canvas.toBlob(async blob=>{if(!blob){toast('画面暂未导出，请重试。');return;}const a=$('image-download');let href;try{const response=await fetch('/__save-preview',{method:'POST',headers:{'Content-Type':'image/png'},body:blob});const result=await response.json();if(response.ok&&result.saved)href=`./${result.path}?v=${Date.now()}`;}catch{}if(!href)href=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(blob);});a.href=href;a.download=`共知会议-${state.phase}-${state.count}人.png`;a.hidden=false;stage.dataset.pngBytes=String(blob.size);stage.dataset.pngType=blob.type;a.click();toast('画面已生成，可点击保存 PNG');},'image/png');});
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('loading').hidden=false;$('loading-message').textContent='三维绘图已中断，请刷新页面恢复。';state.ready=false;});
}
function expandVisitors(){const group=root.getObjectByName('Conference_People');if(group?.children.length!==96)throw new Error('会议模型缺少完整人物节点');}
async function saveModel(){const button=$('save-model');button.disabled=true;$('build-status').textContent='正在归档完整场景…';try{const [{GLTFExporter},{portableCopy}]=await Promise.all([import('three/addons/exporters/GLTFExporter.js'),import('./model.js?v=1')]);const exportRoot=portableCopy(root);const people=exportRoot.getObjectByName('Conference_People');applyAttendance(exportRoot,100,'launch',true,'lecture');exportRoot.getObjectByName('Conference_Roof').visible=true;const bytes=await new GLTFExporter().parseAsync(exportRoot,{binary:true,onlyVisible:true,animations:[],maxTextureSize:2048});
 const response=await fetch('/__save-conference',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:bytes});const result=await response.json();if(!response.ok||!result.saved)throw new Error(result.error||`HTTP ${response.status}`);$('build-status').textContent=`已保存 conference.glb · ${(bytes.byteLength/1024/1024).toFixed(2)} MB`;stage.dataset.saved='true';stage.dataset.modelBytes=String(bytes.byteLength);$('download').removeAttribute('aria-disabled');toast('完整会议场景已归档');
 }catch(e){$('build-status').textContent=`保存失败：${e.message}`;console.error(e);}finally{button.disabled=false;}}
async function initialize(){renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.07;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;
 scene=new THREE.Scene();scene.background=new THREE.Color('#dfe5e9');perspective=new THREE.PerspectiveCamera(36,1,.06,180);ortho=new THREE.OrthographicCamera(-8,8,5.3,-5.3,.05,180);camera=perspective;controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.09;controls.screenSpacePanning=false;controls.addEventListener('change',invalidate);controls.addEventListener('start',()=>canvas.style.cursor='grabbing');controls.addEventListener('end',()=>canvas.style.cursor='grab');
 const hemi=new THREE.HemisphereLight('#fff9e7','#9eaa94',.8);scene.add(hemi);sun=new THREE.DirectionalLight('#fff0d6',2.5);sun.position.set(-12,24,16);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-22,right:22,top:22,bottom:-22,near:.5,far:75});sun.shadow.normalBias=.028;sun.shadow.bias=-.0001;scene.add(sun);const fill=new THREE.DirectionalLight('#f0f4ed',.65);fill.position.set(7,6,-1);scene.add(fill);
 const pm=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();environment=pm.fromScene(room,.05);scene.environment=environment.texture;scene.environmentIntensity=.7;pm.dispose();room.dispose();
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:'#dfe5e9',roughness:.95}));ground.rotation.x=-Math.PI/2;ground.position.y=-.27;ground.receiveShadow=true;scene.add(ground);
 bind();new ResizeObserver(resize).observe(stage);resize();
 if(buildMode){$('build-bar').hidden=false;$('download').setAttribute('aria-disabled','true');const {buildConference}=await import('./model.js?v=1');await document.fonts.ready;root=await buildConference();$('save-model').disabled=false;$('save-model').addEventListener('click',saveModel);}
 else{const gltf=await new GLTFLoader().loadAsync('./conference.glb');root=gltf.scene.getObjectByName('Conference_24x18');if(!root)throw new Error('模型不是完整会议模板');expandVisitors();}
 root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});root.getObjectByName('Conference_Roof').visible=state.rig;scene.add(root);report=sceneReport(root);
 for(const zone of ZONES){const element=document.createElement('span');element.className='scene-label';const number=document.createElement('b');number.textContent=zone.n;const title=document.createElement('span');title.textContent=zone.title;element.append(number,title);$('labels-layer').append(element);labels.push({element,point:new THREE.Vector3(...zone.point).add(new THREE.Vector3(0,.35,0))});}
 state.ready=true;$('loading').hidden=true;$('load-status').textContent=buildMode?'完整场景已构建':'完整模型已载入';Object.assign(stage.dataset,{ready:'true',modelSource:buildMode?'build':'conference.glb',meshes:String(report.meshes),triangles:String(report.triangles)});updateAttendance();setView('overview');
 const details=document.createElement('script');details.type='application/json';details.id='scene-validation';details.textContent=JSON.stringify(report);document.body.append(details);
}
initialize().catch(e=>{$('loading').hidden=false;$('loading-message').textContent=`暂未载入：${e.message}`;$('load-status').textContent='场景载入失败';console.error(e);});
