import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {sceneReport} from './model.js';
const $=id=>document.getElementById(id),canvas=$('scene'),stage=$('stage');
const buildMode=new URLSearchParams(location.search).get('build')==='1';
const state={view:'overview',roof:false,ready:false};
let renderer,scene,camera,perspective,ortho,controls,root,frame=null,w=1,h=1;
const names={overview:'整体视角',top:'俯视布局',inside:'场内视角'};
function invalidate(){if(frame===null)frame=requestAnimationFrame(render);}
function render(){frame=null;const moving=controls.update();renderer.render(scene,camera);stage.dataset.camera=camera.position.toArray().map(v=>v.toFixed(3)).join(',');stage.dataset.zoom=String(camera.zoom);if(moving)invalidate();}
function setView(view){state.view=view;const damping=controls.enableDamping;controls.enableDamping=false;controls.update();camera=view==='top'?ortho:perspective;controls.object=camera;controls.enableRotate=view!=='top';controls.minDistance=view==='inside'?.3:3;controls.maxDistance=60;controls.minZoom=.6;controls.maxZoom=5;controls.maxPolarAngle=view==='inside'?Math.PI*.57:Math.PI*.48;
 if(view==='top'){camera.position.set(0,24,.001);controls.target.set(0,0,0);camera.zoom=1;}
 else if(view==='inside'){camera.fov=67;camera.position.set(3.35,1.6,3.55);controls.target.set(-.7,1.25,-2.65);}
 else{camera.fov=37;const fit=Math.max(1,1.15/(w/h));camera.position.set(13.5*fit,12.5*fit,16.5*fit);controls.target.set(0,.9,0);}
 camera.updateProjectionMatrix();controls.update();controls.enableDamping=damping;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));$('view-label').textContent=names[view];stage.dataset.view=view;invalidate();}
function resize(){const rect=stage.getBoundingClientRect();w=Math.max(1,rect.width);h=Math.max(1,rect.height);renderer.setSize(w,h,false);perspective.aspect=w/h;perspective.updateProjectionMatrix();const half=Math.max(5.35,7.25/(w/h));ortho.left=-half*w/h;ortho.right=half*w/h;ortho.top=half;ortho.bottom=-half;ortho.updateProjectionMatrix();if(state.view==='overview')setView('overview');else invalidate();}
async function saveModel(){const button=$('save-model');button.disabled=true;$('build-status').textContent='正在归档独立场景…';try{const [{GLTFExporter},{portableCopy}]=await Promise.all([import('three/addons/exporters/GLTFExporter.js'),import('./model.js')]);const copy=portableCopy(root);copy.getObjectByName('Cafe_Roof').visible=true;const bytes=await new GLTFExporter().parseAsync(copy,{binary:true,onlyVisible:true,maxTextureSize:2048});const response=await fetch('/__save-cafe',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:bytes});const result=await response.json();if(!response.ok||!result.saved)throw new Error(result.error||`HTTP ${response.status}`);$('build-status').textContent=`已保存 cafe.glb · ${(bytes.byteLength/1048576).toFixed(2)} MiB`;Object.assign(stage.dataset,{saved:'true',modelBytes:String(bytes.byteLength),modelSha256:result.sha256});$('download').removeAttribute('aria-disabled');}catch(e){$('build-status').textContent=`保存失败：${e.message}`;console.error(e);}finally{button.disabled=false;}}
async function initialize(){renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;
 scene=new THREE.Scene();scene.background=new THREE.Color('#e8e9e2');perspective=new THREE.PerspectiveCamera(37,1,.03,120);ortho=new THREE.OrthographicCamera(-8,8,6,-6,.03,120);camera=perspective;controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.1;controls.screenSpacePanning=false;controls.addEventListener('change',invalidate);controls.addEventListener('start',()=>canvas.style.cursor='grabbing');controls.addEventListener('end',()=>canvas.style.cursor='grab');
 scene.add(new THREE.HemisphereLight('#fff8e9','#aaac95',.9));const sun=new THREE.DirectionalLight('#fff3d8',2.4);sun.position.set(8,12,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-10,right:10,top:10,bottom:-10,near:.5,far:40});sun.shadow.normalBias=.012;sun.shadow.bias=-.0001;scene.add(sun);const fill=new THREE.DirectionalLight('#eff4e8',.6);fill.position.set(-5,5,2);scene.add(fill);
 const pm=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pm.fromScene(room,.04).texture;scene.environmentIntensity=.52;pm.dispose();room.dispose();const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:'#e8e9e2',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.17;ground.receiveShadow=true;scene.add(ground);
 document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('reset').addEventListener('click',()=>setView('overview'));$('roof').addEventListener('change',e=>{state.roof=e.target.checked;if(root)root.getObjectByName('Cafe_Roof').visible=state.roof;stage.dataset.roof=String(state.roof);invalidate();});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();state.ready=false;stage.dataset.ready='false';$('loading').hidden=false;$('loading-message').textContent='三维绘图已中断，请刷新恢复。';});new ResizeObserver(resize).observe(stage);resize();
 if(buildMode){$('build-bar').hidden=false;$('download').setAttribute('aria-disabled','true');const {buildCafe}=await import('./model.js');await document.fonts.ready;root=await buildCafe();$('save-model').disabled=false;$('save-model').addEventListener('click',saveModel);}
 else{const gltf=await new GLTFLoader().loadAsync('./cafe.glb');root=gltf.scene.getObjectByName('Cafe_12x9');if(!root)throw new Error('缺少完整咖啡店根节点');}
 root.traverse(o=>{if(o.isMesh){o.castShadow=!o.material?.transparent;o.receiveShadow=true;}});root.getObjectByName('Cafe_Roof').visible=state.roof;scene.add(root);const report=sceneReport(root);const details=document.createElement('script');details.id='scene-validation';details.type='application/json';details.textContent=JSON.stringify(report);document.body.append(details);Object.assign(stage.dataset,{ready:'true',modelSource:buildMode?'build':'cafe.glb',meshInstances:String(report.meshes),triangles:String(report.triangles),editableObjects:String(report.editableObjects),roof:String(state.roof)});state.ready=true;$('loading').hidden=true;$('load-status').textContent=buildMode?'完整模型已构建':'完整 GLB 已载入';setView('overview');
}
initialize().catch(e=>{$('loading').hidden=false;$('loading-message').textContent=`暂未载入：${e.message}`;$('load-status').textContent='载入失败';console.error(e);});
