#!/usr/bin/env node
// node validation/validate-glb.mjs [cafe.glb] [existing gltf-validator package]
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { inspectGLB,serializeBounds,round } from './check-layout.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),file=path.resolve(process.argv[2]||path.join(here,'../cafe.glb'));
const require=createRequire(import.meta.url),candidate=process.argv[3]||process.env.GLTF_VALIDATOR_MODULE||path.resolve(here,'../../../scendance-frontend/node_modules/gltf-validator');
let validator;try{validator=require(candidate);}catch{try{validator=require('gltf-validator');}catch{throw new Error('Existing gltf-validator package not found. Pass its directory as the second argument or GLTF_VALIDATOR_MODULE. The portable preview does not require Node or this validator.');}}
const inspection=inspectGLB(file),{doc,bytes,records,root}=inspection;
const official=await validator.validateBytes(new Uint8Array(bytes),{uri:path.basename(file),format:'glb',maxIssues:0,externalResourceFunction:async uri=>{throw new Error(`Unexpected external resource: ${uri}`);}});
await fs.writeFile(path.join(here,'gltf-validation.json'),JSON.stringify(official,null,2)+'\n');
const expected=['Cafe_12x9','Cafe_Structure','Cafe_Furniture','Cafe_Equipment','Cafe_Lighting','Cafe_Roof'];
const groups=expected.map(name=>{const matches=records.filter(r=>r.name===name),r=matches[0];return{name,present:matches.length===1,matches:matches.length,children:r?.node.children?.length||0,worldBounds:serializeBounds(r?.bounds)};});
const editable=records.filter(r=>r.node.extras?.editableObject),names=new Map();for(const r of editable)names.set(r.name,(names.get(r.name)||0)+1);
const duplicateEditableNames=[...names.entries()].filter(([name,count])=>!name||count!==1).map(([name,count])=>({name,count}));
const inventory=root?.node.extras?.inventory||[],inventoryItems=Array.isArray(inventory)?inventory:Object.entries(inventory).map(([name,value])=>typeof value==='object'?{name,...value}:{name,count:value});
const inventoryChecks=inventoryItems.map(item=>{const name=typeof item==='string'?item:item.objectName||item.nodeName||item.name||item.id;const matches=editable.filter(r=>r.name===name||r.node.extras.objectId===name);return{name,matched:matches.length===1,actualRole:matches[0]?.node.extras.role||null,declaredRole:typeof item==='object'?item.role||null:null};});
const duplicateInventoryNames=inventoryChecks.map(i=>i.name).filter((name,i,names)=>!name||names.indexOf(name)!==i);
const missingInventory=editable.filter(r=>!inventoryChecks.some(i=>i.name===r.name||i.name===r.node.extras.objectId)).map(r=>r.name);
const imageChecks=(doc.images||[]).map((im,index)=>({index,name:im.name||'',mimeType:im.mimeType||null,embedded:im.bufferView!==undefined||Boolean(im.uri?.startsWith('data:')),bytes:im.bufferView!==undefined?doc.bufferViews[im.bufferView].byteLength:null}));
const externalResources=[];for(const kind of ['buffers','images'])for(const [index,r]of(doc[kind]||[]).entries())if(r.uri&&!r.uri.startsWith('data:'))externalResources.push({kind,index,uri:r.uri});
const roles={};for(const r of editable){const role=r.node.extras.role||'missing';roles[role]=(roles[role]||0)+1;}
const issueCodes={};for(const i of official.issues.messages||[])issueCodes[i.code]=(issueCodes[i.code]||0)+1;
const metadata=root?.node.extras||{};
const countChecks=Object.fromEntries([...new Set([...Object.keys(metadata.counts||{}),...Object.keys(roles)])].map(role=>[role,{declared:metadata.counts?.[role]??null,actual:roles[role]||0,matches:metadata.counts?.[role]===(roles[role]||0)}]));
const checks={gltfVersion2:doc.asset.version==='2.0',oneDefaultScene:(doc.scenes||[]).length===1,requiredGroups:groups.every(g=>g.present),noValidatorErrors:official.issues.numErrors===0,noValidatorWarnings:official.issues.numWarnings===0,validatorNotTruncated:!official.issues.truncated,noExternalResources:externalResources.length===0,allImagesEmbedded:imageChecks.every(i=>i.embedded),hasEmbeddedArtwork:imageChecks.length>0,conceptDimensions:metadata.width===12&&metadata.depth===9&&(metadata.height===3.25||metadata.ceilingHeight===3.25||metadata.designHeight===3.25),staticGeometrySupported:inspection.unsupported.length===0,finiteWorldGeometry:inspection.issues.length===0,uniqueEditableNames:duplicateEditableNames.length===0,uniqueInventoryNames:duplicateInventoryNames.length===0,declaredCountsMatch:Object.keys(countChecks).length>0&&Object.values(countChecks).every(c=>c.matches),inventoryRolesMatch:inventoryChecks.every(i=>i.actualRole===i.declaredRole),editableObjectsHaveRole:editable.every(r=>typeof r.node.extras.role==='string'&&r.node.extras.role.length>0),editableObjectsHaveGeometry:editable.every(r=>!r.bounds.isEmpty()),inventoryPresent:inventoryItems.length>0,inventoryMatchesExport:inventoryChecks.every(i=>i.matched)&&missingInventory.length===0,hasEditableFurniture:editable.length>0,noAnimations:(doc.animations||[]).length===0};
const report={checkedAt:new Date().toISOString(),file:path.basename(file),bytes:bytes.length,sha256:inspection.sha256,gltfVersion:doc.asset.version,generator:doc.asset.generator,chunks:inspection.chunks,nodeCount:doc.nodes.length,reachableNodes:records.length,uniqueMeshes:doc.meshes?.length||0,meshInstances:inspection.meshInstances,primitiveInstances:inspection.primitiveInstances,triangleInstances:inspection.triangleInstances,vertexInstances:inspection.vertexInstances,materials:doc.materials?.length||0,textures:doc.textures?.length||0,images:imageChecks.length,embeddedImages:imageChecks.filter(i=>i.embedded).length,imageChecks,externalResources,extensionsUsed:doc.extensionsUsed||[],extensionsRequired:doc.extensionsRequired||[],worldBounds:serializeBounds(inspection.bounds),groups,rootMetadata:metadata,editableObjectCount:editable.length,editableRoleCounts:roles,editableInventory:editable.map(r=>({name:r.name,role:r.node.extras.role,parent:inspection.byIndex.get(r.parent)?.name||null,position:r.position.toArray().map(round),worldBounds:serializeBounds(r.bounds),meshInstances:r.descendantMeshes.length,metadata:r.node.extras})),duplicateEditableNames,duplicateInventoryNames,countChecks,inventoryChecks,missingInventory,unsupported:inspection.unsupported,geometryIssues:inspection.issues,validator:{version:validator.version(),errors:official.issues.numErrors,warnings:official.issues.numWarnings,infos:official.issues.numInfos,hints:official.issues.numHints,truncated:official.issues.truncated,issueCodes},checks,passed:Object.values(checks).every(Boolean),limitations:['Reports the actual exported static default scene; viewer interactions are checked separately in the browser.','Editable object names must be unique; shared nested asset mesh names are permitted.','Concept dimensions and static geometry checks do not establish measured building dimensions or any regulatory approval.']};
await fs.writeFile(path.join(here,'model-validation.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({file:report.file,bytes:report.bytes,sha256:report.sha256,meshInstances:report.meshInstances,triangleInstances:report.triangleInstances,editableObjectCount:report.editableObjectCount,editableRoleCounts:roles,embeddedImages:report.embeddedImages,externalResources:externalResources.length,validator:report.validator,checks,passed:report.passed},null,2));
if(!report.passed)process.exitCode=1;
