import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { ZONES, PHASES, applyAttendance, sceneReport } from './model.js?v=2';

const $=id=>document.getElementById(id),canvas=$('scene'),stage=$('stage');
const buildMode=new URLSearchParams(location.search).get('build')==='1';
const state={view:'overview',phase:'open',count:24,labels:true,people:true,rig:false,ready:false};
let renderer,scene,camera,controls,root,sun,environment,frame=null;
let ortho,perspective,width=1,height=1,report=null;
const labels=[];const names={overview:'整体视角',top:'俯视布局',inside:'场内视角'};
function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,2800);}
function invalidate(){if(frame===null)frame=requestAnimationFrame(render);}
function render(){frame=null;const moving=controls.update();renderer.render(scene,camera);updateLabels();if(moving)invalidate();}
function updateLabels(){for(const {element,point} of labels){const p=point.clone().project(camera);element.hidden=!state.labels||state.view==='inside'||p.z>1||p.z< -1||Math.abs(p.x)>1||Math.abs(p.y)>1;element.style.left=`${(p.x*.5+.5)*width}px`;element.style.top=`${(-p.y*.5+.5)*height}px`;}}
function resize(){const rect=stage.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);renderer.setSize(width,height,false);perspective.aspect=width/height;perspective.updateProjectionMatrix();const half=Math.max(5.2,7.15/(width/height));ortho.left=-half*width/height;ortho.right=half*width/height;ortho.top=half;ortho.bottom=-half;ortho.updateProjectionMatrix();if(state.view==='overview')setView('overview');else invalidate();}
function setView(view){state.view=view;const damping=controls.enableDamping;controls.enableDamping=false;controls.update();camera=view==='top'?ortho:perspective;controls.object=camera;controls.enableRotate=view!=='top';controls.minDistance=view==='inside'?.4:4;controls.maxDistance=45;controls.minZoom=.55;controls.maxZoom=5;controls.maxPolarAngle=view==='inside'?Math.PI*.54:Math.PI*.48;
 if(view==='top'){camera.position.set(.2,26,.001);controls.target.set(.2,0,0);camera.zoom=1;}
 else if(view==='inside'){camera.fov=68;camera.position.set(.3,1.7,3.65);controls.target.set(.25,1.32,-1.55);}
 else{camera.fov=36;const fit=Math.max(1,1.24/(width/height));controls.target.set(0,.64,.12);camera.position.set(13*fit,12.5*fit,17.5*fit);}
 camera.updateProjectionMatrix();controls.update();controls.enableDamping=damping;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));$('view-label').textContent=names[view];stage.dataset.view=view;invalidate();}
function updateAttendance(){if(!root)return;const visible=applyAttendance(root,state.count,state.phase,state.people);$('guest-total').innerHTML=`${state.count}<small> 人</small>`;$('count-value').textContent=state.count;$('phase-clock').textContent=PHASES[state.phase].clock;$('phase-description').textContent=PHASES[state.phase].text;$('attendance-note').textContent=PHASES[state.phase].guestVisible?`${state.count} 位来访者 + 2 位店员 · 调整人数更新人物分布，展台布局保持固定。`:'此阶段暂无来访者入场 · 2 位店员在场 · 人物位置用于流程演示。';
 document.querySelectorAll('[data-phase]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.phase===state.phase)));
 const closed=state.phase==='closed';sun.intensity=closed?1.1:2.5;scene.environmentIntensity=closed?.24:.42;renderer.toneMappingExposure=closed?.73:.91;
 Object.assign(stage.dataset,{phase:state.phase,visitors:String(state.count),visiblePeople:String(visible),view:state.view,rig:String(state.rig)});invalidate();}
function selectZone(id){const zone=ZONES.find(z=>z.id===id);document.querySelectorAll('[data-zone]').forEach(b=>b.classList.toggle('active',b.dataset.zone===id));$('selection').hidden=!zone;if(!zone)return;$('selection-number').textContent=`ZONE / ${zone.n}`;$('selection-title').textContent=zone.title;$('selection-copy').textContent=zone.copy;invalidate();}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-phase]').forEach(b=>b.addEventListener('click',()=>{state.phase=b.dataset.phase;updateAttendance();}));document.querySelectorAll('[data-zone]').forEach(b=>b.addEventListener('click',()=>selectZone(b.dataset.zone)));$('close-selection').addEventListener('click',()=>selectZone(null));$('reset').addEventListener('click',()=>{setView('overview');selectZone(null);});$('labels').addEventListener('change',e=>{state.labels=e.target.checked;invalidate();});$('people').addEventListener('change',e=>{state.people=e.target.checked;updateAttendance();});$('rig').addEventListener('change',e=>{state.rig=e.target.checked;if(root)root.getObjectByName('Popup_LightingRig').visible=state.rig;stage.dataset.rig=String(state.rig);invalidate();});$('guest-count').addEventListener('input',e=>{state.count=Number(e.target.value);updateAttendance();});
 $('snapshot').addEventListener('click',()=>{if(!state.ready)return;renderer.render(scene,camera);canvas.toBlob(blob=>{if(!blob){toast('画面暂未导出，请重试。');return;}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`青序快闪-${state.phase}-${state.count}人.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);toast('已导出当前三维画面');},'image/png');});
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('loading').hidden=false;$('loading-message').textContent='三维绘图已中断，请刷新页面恢复。';state.ready=false;});
}
function expandVisitors(){const group=root.getObjectByName('Popup_People');if(!group||group.children.length<24)throw new Error('快闪归档缺少 24 位来访者节点');while(group.children.length<30){const i=group.children.length,copy=group.children[i%24].clone(true);copy.name=`Visitor_${String(i+1).padStart(2,'0')}`;group.add(copy);}}
async function saveModel(){const button=$('save-model');button.disabled=true;$('build-status').textContent='正在归档完整场景…';try{const [{GLTFExporter},{portableCopy}]=await Promise.all([import('three/addons/exporters/GLTFExporter.js'),import('./model.js?v=2')]);const exportRoot=portableCopy(root);const people=exportRoot.getObjectByName('Popup_People');for(const p of people.children.slice(24))people.remove(p);applyAttendance(exportRoot,24,'open',true);exportRoot.getObjectByName('Popup_LightingRig').visible=true;const bytes=await new GLTFExporter().parseAsync(exportRoot,{binary:true,onlyVisible:true,animations:[],maxTextureSize:2048});
 const response=await fetch('/__save-popup',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:bytes});const result=await response.json();if(!response.ok||!result.saved)throw new Error(result.error||`HTTP ${response.status}`);$('build-status').textContent=`已保存 popup.glb · ${(bytes.byteLength/1024/1024).toFixed(2)} MB`;stage.dataset.saved='true';stage.dataset.modelBytes=String(bytes.byteLength);$('download').removeAttribute('aria-disabled');toast('完整快闪场景已归档');
 }catch(e){$('build-status').textContent=`保存失败：${e.message}`;console.error(e);}finally{button.disabled=false;}}
async function initialize(){renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.07;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;
 scene=new THREE.Scene();scene.background=new THREE.Color('#e5e6dc');perspective=new THREE.PerspectiveCamera(36,1,.06,180);ortho=new THREE.OrthographicCamera(-8,8,5.3,-5.3,.05,180);camera=perspective;controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.09;controls.screenSpacePanning=false;controls.addEventListener('change',invalidate);controls.addEventListener('start',()=>canvas.style.cursor='grabbing');controls.addEventListener('end',()=>canvas.style.cursor='grab');
 const hemi=new THREE.HemisphereLight('#fff9e7','#9eaa94',.8);scene.add(hemi);sun=new THREE.DirectionalLight('#fff0d6',2.5);sun.position.set(-3,12,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-10,right:10,top:9,bottom:-9,near:.5,far:36});sun.shadow.normalBias=.028;sun.shadow.bias=-.0001;scene.add(sun);const fill=new THREE.DirectionalLight('#f0f4ed',.65);fill.position.set(7,6,-1);scene.add(fill);
 const pm=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();environment=pm.fromScene(room,.05);scene.environment=environment.texture;scene.environmentIntensity=.7;pm.dispose();room.dispose();
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:'#e5e6dc',roughness:.95}));ground.rotation.x=-Math.PI/2;ground.position.y=-.19;ground.receiveShadow=true;scene.add(ground);
 bind();new ResizeObserver(resize).observe(stage);resize();
 if(buildMode){$('build-bar').hidden=false;$('download').setAttribute('aria-disabled','true');const {buildPopup}=await import('./model.js?v=2');await document.fonts.ready;root=await buildPopup();$('save-model').disabled=false;$('save-model').addEventListener('click',saveModel);}
 else{const gltf=await new GLTFLoader().loadAsync('./popup.glb?v=763140418e1e');root=gltf.scene.getObjectByName('Popup_NatureFragrance_12x8');if(!root)throw new Error('模型不是完整快闪模板');expandVisitors();}
 root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});root.getObjectByName('Popup_LightingRig').visible=false;scene.add(root);report=sceneReport(root);
 for(const zone of ZONES){const element=document.createElement('span');element.className='scene-label';const number=document.createElement('b');number.textContent=zone.n;const title=document.createElement('span');title.textContent=zone.title;element.append(number,title);$('labels-layer').append(element);labels.push({element,point:new THREE.Vector3(...zone.point).add(new THREE.Vector3(0,.35,0))});}
 state.ready=true;$('loading').hidden=true;$('load-status').textContent=buildMode?'真实素材已就绪':'完整模型已载入';Object.assign(stage.dataset,{ready:'true',modelSource:buildMode?'build':'popup.glb',meshes:String(report.meshes),triangles:String(report.triangles)});updateAttendance();setView('overview');
 const details=document.createElement('script');details.type='application/json';details.id='scene-validation';details.textContent=JSON.stringify(report);document.body.append(details);
}
initialize().catch(e=>{$('loading').hidden=false;$('loading-message').textContent=`暂未载入：${e.message}`;$('load-status').textContent='场景载入失败';console.error(e);});
